apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  type: ClusterIP
  selector:
    app: db
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.db.port }}
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db-dpl
spec:
  selector:
    matchLabels:
      app: db
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: db
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: db
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: database

