apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  username: {{ .Values.db.username }}
  password: {{ .Values.db.password }}
  database: {{ .Values.db.database }}
