{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "linkd.serviceAccountName" . }}
  labels:
{{ include "linkd.labels" . | nindent 4 }}
{{- end -}}
