apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bot
spec:
  selector:
    matchLabels:
      app: cardinal
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: cardinal
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: cardinal
          image: hbjy/cardinal:v1.2.2
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: discordToken
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: databaseUri
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: sentryDsn
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: environment
            - name: PREFIX
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: prefix
            - name: OWNERS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: botOwners
