apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  discordToken: {{ .Values.token }}
  databaseUri: {{ .Values.dbUri }}
  sentryDsn: {{ .Values.sentryDsn }}
